<?php
/** @var Kash_Gateway_Block_Review */
?>
<div class="page-title">
    <h1><?php echo $this->__('Complete Order') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<?php if ($this->getShippingAddress()): ?>
    <div class="info-set col2-set">
        <div class="col-1">
            <div class="box">
                <div class="box-title">
                    <h3><?php echo $this->__('Shipping Address') ?><span class="separator"><?php if ($this->getCanEditShippingAddress()):?> | </span><a href="<?php echo $this->getEditUrl() ?>"><?php echo $this->__('Edit') ?></a><?php endif;?></h3>
                </div>
                <div class="box-content">
                    <address><?php echo $this->renderAddress($this->getShippingAddress())?></address>
                </div>
            </div>
        </div>
        <div class="col-2">
            <div class="box">
                <div class="box-title">
                    <h3><?php echo $this->__('Shipping Method') ?></h3>
                </div>
                <div class="box-content">
                        <?php if ($this->getCanEditShippingMethod() || !$this->getCurrentShippingRate()):?>
                            <?php if ($groups = $this->getShippingRateGroups()):?>
                                <?php $currentRate = $this->getCurrentShippingRate(); ?>
                                <fieldset>
                                    <select name="shipping_method" id="shipping_method" style="width:250px;" class="required-entry">
                                        <?php if (!$currentRate):?>
                                            <option value=""><?php echo $this->__('Please select a shipping method...') ?></option>
                                        <?php endif;?>
                                        <?php foreach ($groups as $code => $rates):?>
                                            <optgroup label="<?php echo $this->escapeHtml($this->getCarrierName($code)) ?>" style="font-style:normal;">
                                                <?php foreach ($rates as $rate):?>
                                                    <option value="<?php echo $this->renderShippingRateValue($rate)?>"<?php echo ($currentRate === $rate) ? ' selected="selected"' : '' ;?>>
                                                        <?php echo $this->renderShippingRateOption($rate)?>
                                                    </option>
                                                <?php endforeach;?>
                                            </optgroup>
                                        <?php endforeach;?>
                                    </select>
                                </fieldset>
                            <?php endif;?>
                        <?php else: ?>
                            <p><strong><?php echo $this->renderShippingRateOption($this->getCurrentShippingRate())?></strong></p>
                        <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>


<div class="info-set">
    <div id="details-reload">
        <?php echo $this->getChildHtml('details') ?>
    </div>
</div>

<div class="buttons-set buttons-set-order" id="review-buttons-container">
    <button type="button" id="review_button" onclick="window.location.href='<?php echo Mage::getUrl('checkout/onepage/success'); ?>'" value="<?php echo $this->__('Close') ?>" class="button btn-checkout"><span><span><?php echo $this->__('Close') ?></span></span></button>
</div>

